function createfigure(X1, ymatrix1, Parent1)
%CREATEFIGURE(X1, YMATRIX1, PARENT1)
%  X1:  stairs x
%  YMATRIX1:  stairs matrix data
%  PARENT1:  text parent

%  Auto-generated by MATLAB on 08-Apr-2018 17:40:52

% Create figure
figure('Tag','ScopePrintToFigure',...
    'Color',[0.156862745098039 0.156862745098039 0.156862745098039],...
    'OuterPosition',[544 321 834 566]);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uipanel currently does not support code generation, enter 'doc uipanel' for correct input syntax
% In order to generate code for uipanel, you may use GUIDE. Enter 'doc guide' for more information
% uipanel(...);

% Create axes
axes1 = axes('ColorOrder',...
    [1 1 0.0666666666666667;0.0745098039215686 0.623529411764706 1;1 0.411764705882353 0.16078431372549;0.392156862745098 0.831372549019608 0.0745098039215686;0.717647058823529 0.274509803921569 1;0.0588235294117647 1 1;1 0.0745098039215686 0.650980392156863],...
    'Tag','DisplayAxes1_RealMag');
hold(axes1,'on');

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create multiple lines using matrix input to stairs
stairs1 = stairs(X1,ymatrix1,'LineWidth',0.75,'Parent',axes1);
set(stairs1(1),'DisplayName','Gain1','Tag','DisplayLine1',...
    'Color',[1 1 0.0666666666666667]);
set(stairs1(2),'DisplayName','Gain2','Tag','DisplayLine2',...
    'Color',[0.0745098039215686 0.623529411764706 1]);
set(stairs1(3),'DisplayName','Gain3','Tag','DisplayLine3',...
    'Color',[1 0.411764705882353 0.16078431372549]);
set(stairs1(4),'DisplayName','Gain4','Tag','DisplayLine4',...
    'Color',[0.392156862745098 0.831372549019608 0.0745098039215686]);

% Create xlabel
xlabel('Time (second)');
ylabel('Theta (radians)');
legend('check variable','Joint 1','Joint 2','Joint 3');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[2.08333333333333 44.198717948718]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.198755331753555 0.804652251184834]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'ClippingStyle','rectangle','Color',[0 0 0],'FontSize',8,...
    'GridAlpha',0.4,'GridColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922],...
    'TickLabelInterpreter','none','XColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922],'XGrid','on',...
    'YColor',[0.686274509803922 0.686274509803922 0.686274509803922],'YGrid',...
    'on','ZColor',[0.686274509803922 0.686274509803922 0.686274509803922]);
% Create text
text('Parent',Parent1,'Tag','TimeOffsetStatus','Units','pixels',...
    'VerticalAlignment','bottom',...
    'FontSize',8,...
    'String','Offset=0',...
    'Position',[0 0 0],...
    'Color',[0.686274509803922 0.686274509803922 0.686274509803922],...
    'Visible','on');

