set MATLAB=C:\MATLABR2017a
"C:\MATLAB~1\bin\win64\gmake" -f simulink5ms_plotAndGains.mk  ISPROTECTINGMODEL=NOTPROTECTING EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 TMW_EXTMODE_TESTING=0 OPTS="-DTGTCONN -DON_TARGET_WAIT_FOR_START=1"
