// Generated by gencpp from file ece470_ur3_driver/command.msg
// DO NOT EDIT!


#ifndef ECE470_UR3_DRIVER_MESSAGE_COMMAND_H
#define ECE470_UR3_DRIVER_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ece470_ur3_driver
{
template <class ContainerAllocator>
struct command_
{
  typedef command_<ContainerAllocator> Type;

  command_()
    : destination()
    , grip(0)
    , softhome(0)
    , duration(0.0)  {
    }
  command_(const ContainerAllocator& _alloc)
    : destination(_alloc)
    , grip(0)
    , softhome(0)
    , duration(0.0)  {
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _destination_type;
  _destination_type destination;

   typedef int32_t _grip_type;
  _grip_type grip;

   typedef int32_t _softhome_type;
  _softhome_type softhome;

   typedef double _duration_type;
  _duration_type duration;




  typedef boost::shared_ptr< ::ece470_ur3_driver::command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ece470_ur3_driver::command_<ContainerAllocator> const> ConstPtr;

}; // struct command_

typedef ::ece470_ur3_driver::command_<std::allocator<void> > command;

typedef boost::shared_ptr< ::ece470_ur3_driver::command > commandPtr;
typedef boost::shared_ptr< ::ece470_ur3_driver::command const> commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ece470_ur3_driver::command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ece470_ur3_driver::command_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ece470_ur3_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ece470_ur3_driver': ['/home/youbot/edvall2_catkin/src/drivers/ece470_ur3_driver/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ece470_ur3_driver::command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ece470_ur3_driver::command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece470_ur3_driver::command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece470_ur3_driver::command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece470_ur3_driver::command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece470_ur3_driver::command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ece470_ur3_driver::command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d2c2700daec81019d4338afb533bad6";
  }

  static const char* value(const ::ece470_ur3_driver::command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d2c2700daec8101ULL;
  static const uint64_t static_value2 = 0x9d4338afb533bad6ULL;
};

template<class ContainerAllocator>
struct DataType< ::ece470_ur3_driver::command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ece470_ur3_driver/command";
  }

  static const char* value(const ::ece470_ur3_driver::command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ece470_ur3_driver::command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] destination\n\
int32 grip\n\
int32 softhome\n\
float64 duration\n\
";
  }

  static const char* value(const ::ece470_ur3_driver::command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ece470_ur3_driver::command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.destination);
      stream.next(m.grip);
      stream.next(m.softhome);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ece470_ur3_driver::command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ece470_ur3_driver::command_<ContainerAllocator>& v)
  {
    s << indent << "destination[]" << std::endl;
    for (size_t i = 0; i < v.destination.size(); ++i)
    {
      s << indent << "  destination[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.destination[i]);
    }
    s << indent << "grip: ";
    Printer<int32_t>::stream(s, indent + "  ", v.grip);
    s << indent << "softhome: ";
    Printer<int32_t>::stream(s, indent + "  ", v.softhome);
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECE470_UR3_DRIVER_MESSAGE_COMMAND_H
